name: Docker Build

on:
  push:
    branches: [ dev, staging, main, feature/* ]
  pull_request:
    branches: [ dev, staging, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t my-app:latest .
